# AUTOGENERATED FROM packages/ir-schema/schema/architecture-ir.schema.json - DO NOT EDIT
# Regenerate with: pnpm --filter @infracanvas/ir-schema generate

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ResourceId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9][a-z0-9-]{0,62}$")]


class ResourceKind(
    RootModel[
        Literal[
            "vpc",
            "subnet",
            "internet_gateway",
            "nat_gateway",
            "security_group",
            "ec2_instance",
            "lambda_function",
            "ecs_cluster",
            "ecs_service",
            "alb",
            "nlb",
            "api_gateway",
            "cloudfront_distribution",
            "route53_zone",
            "s3_bucket",
            "rds_instance",
            "dynamodb_table",
            "elasticache_cluster",
            "sns_topic",
            "sqs_queue",
            "iam_role",
            "cognito_user_pool",
            "cloudwatch_log_group",
            "secretsmanager_secret",
        ]
    ]
):
    root: Literal[
        "vpc",
        "subnet",
        "internet_gateway",
        "nat_gateway",
        "security_group",
        "ec2_instance",
        "lambda_function",
        "ecs_cluster",
        "ecs_service",
        "alb",
        "nlb",
        "api_gateway",
        "cloudfront_distribution",
        "route53_zone",
        "s3_bucket",
        "rds_instance",
        "dynamodb_table",
        "elasticache_cluster",
        "sns_topic",
        "sqs_queue",
        "iam_role",
        "cognito_user_pool",
        "cloudwatch_log_group",
        "secretsmanager_secret",
    ]


class Layout(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    x: int
    y: int
    width: Annotated[int | None, Field(ge=1)] = None
    height: Annotated[int | None, Field(ge=1)] = None


class NodeBase(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern="^[a-z0-9][a-z0-9-]{0,62}$")]
    name: Annotated[str, Field(max_length=128, min_length=1)]
    parent: ResourceId | None = None
    layout: Layout | None = None


class VpcParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    cidr_block: Annotated[str, Field(alias="cidrBlock")]
    enable_dns_hostnames: Annotated[bool | None, Field(alias="enableDnsHostnames")] = True
    enable_dns_support: Annotated[bool | None, Field(alias="enableDnsSupport")] = True


class VpcNode(NodeBase):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    kind: Literal["vpc"]
    params: VpcParams


class SubnetParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    tier: Literal["public", "private"]
    cidr_block: Annotated[str, Field(alias="cidrBlock")]
    availability_zone: Annotated[str, Field(alias="availabilityZone", min_length=1)]


class SubnetNode(NodeBase):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    kind: Literal["subnet"]
    params: SubnetParams


class RdsInstanceParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    engine: Literal["postgres", "mysql", "mariadb"]
    engine_version: Annotated[
        str | None, Field(alias="engineVersion", max_length=32, min_length=1)
    ] = None
    instance_class: Annotated[
        str, Field(alias="instanceClass", pattern="^db\\.[a-z0-9]+\\.[a-z0-9]+$")
    ]
    allocated_storage_gb: Annotated[int, Field(alias="allocatedStorageGb", ge=20, le=65536)]
    storage_type: Annotated[
        Literal["gp2", "gp3", "io1", "io2"] | None, Field(alias="storageType")
    ] = "gp3"
    multi_az: Annotated[bool | None, Field(alias="multiAz")] = False
    publicly_accessible: Annotated[bool | None, Field(alias="publiclyAccessible")] = False
    deletion_protection: Annotated[bool | None, Field(alias="deletionProtection")] = False
    backup_retention_days: Annotated[
        int | None, Field(alias="backupRetentionDays", ge=0, le=35)
    ] = 7
    storage_encrypted: Annotated[bool | None, Field(alias="storageEncrypted")] = True


class RdsInstanceNode(NodeBase):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    kind: Literal["rds_instance"]
    params: RdsInstanceParams


class PendingContractNode(NodeBase):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    kind: Annotated[
        Literal[
            "internet_gateway",
            "nat_gateway",
            "security_group",
            "ec2_instance",
            "lambda_function",
            "ecs_cluster",
            "ecs_service",
            "alb",
            "nlb",
            "api_gateway",
            "cloudfront_distribution",
            "route53_zone",
            "s3_bucket",
            "dynamodb_table",
            "elasticache_cluster",
            "sns_topic",
            "sqs_queue",
            "iam_role",
            "cognito_user_pool",
            "cloudwatch_log_group",
            "secretsmanager_secret",
        ],
        Field(
            description="Kinds whose parameters are not typed yet, awaiting a resource contract."
        ),
    ]
    params: dict[str, str | float | bool]


class Edge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern="^[a-z0-9][a-z0-9-]{0,62}$")]
    kind: Literal["connects", "depends_on", "routes_to"]
    source: Annotated[str, Field(pattern="^[a-z0-9][a-z0-9-]{0,62}$")]
    target: Annotated[str, Field(pattern="^[a-z0-9][a-z0-9-]{0,62}$")]
    label: Annotated[str | None, Field(max_length=64)] = None
    source_handle: Annotated[str | None, Field(alias="sourceHandle")] = None
    target_handle: Annotated[str | None, Field(alias="targetHandle")] = None


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    x: float
    y: float
    zoom: Annotated[float, Field(gt=0.0)]


class Presentation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    viewport: Viewport | None = None


class ArchitectureIr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    ir_version: Annotated[str, Field(alias="irVersion", pattern="^1\\.\\d+\\.\\d+$")]
    name: Annotated[str, Field(max_length=128, min_length=1)]
    provider: Literal["aws"]
    region: Annotated[str, Field(pattern="^[a-z]{2}(-gov)?-[a-z]+-[0-9]$")]
    nodes: list[VpcNode | SubnetNode | RdsInstanceNode | PendingContractNode]
    edges: list[Edge]
    presentation: Presentation | None = None
