#!/usr/bin/env node
/**
 * Regenerates everything derived from the IR schema.
 *
 * Gate 4's `schema-drift` job runs this and then `git diff --exit-code`, so the
 * output must be deterministic: same schema in, byte-identical files out. Both
 * halves are formatted with this repository's own formatters as the last step,
 * so what is written is what `pnpm format:check` and `ruff format --check`
 * expect.
 *
 *   pnpm --filter @infracanvas/ir-schema generate
 *
 * `--schema <path>` overrides the input. It exists so the failure path can be
 * exercised by a test against a deliberately broken schema; nothing else should
 * use it.
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { compile } from 'json-schema-to-typescript';
import * as prettier from 'prettier';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(packageRoot, '..', '..');

const schemaFlag = process.argv.indexOf('--schema');
const schemaPath =
  schemaFlag >= 0
    ? process.argv[schemaFlag + 1]
    : join(packageRoot, 'schema', 'architecture-ir.schema.json');

const versionPath = join(packageRoot, 'VERSION');
const typesPath = join(packageRoot, 'src', 'generated', 'types.ts');
const versionModulePath = join(packageRoot, 'src', 'generated', 'ir-version.ts');
const pydanticPath = join(repoRoot, 'services', 'brain', 'src', 'brain', 'ir', 'models.py');

const SOURCE = 'packages/ir-schema/schema/architecture-ir.schema.json';
const COMMAND = 'pnpm --filter @infracanvas/ir-schema generate';
const BANNER = [
  `// AUTOGENERATED FROM ${SOURCE} - DO NOT EDIT`,
  `// Regenerate with: ${COMMAND}`,
  '',
];
const PYTHON_BANNER = [
  `# AUTOGENERATED FROM ${SOURCE} - DO NOT EDIT`,
  `# Regenerate with: ${COMMAND}`,
  '',
];

function fail(message) {
  console.error(message);
  process.exit(1);
}

function relative(path) {
  return path.startsWith(repoRoot) ? path.slice(repoRoot.length + 1) : path;
}

// ---------------------------------------------------------------------------
// Everything is produced before anything is written, so a schema that does not
// compile leaves the committed files as they were rather than half rewritten.
// ---------------------------------------------------------------------------

let schema;
try {
  schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
} catch (error) {
  fail(`${schemaPath}: ${error.message}`);
}

const version = readFileSync(versionPath, 'utf8').trim();

if (typeof schema.$id !== 'string') {
  fail(`${schemaPath}: the schema has no $id, so its version cannot be checked`);
}
if (!schema.$id.endsWith(`/${version}.json`)) {
  fail(
    `${schemaPath}: $id is ${schema.$id} but VERSION is ${version}.\n` +
      'Bump one to match the other; the $id is what consumers pin against.'
  );
}

const versionModule = [
  ...BANNER,
  `export const IR_VERSION = '${version}';`,
  `export const IR_SCHEMA_ID = '${schema.$id}';`,
  '',
].join('\n');

let types;
try {
  types = await compile(schema, 'ArchitectureIr', {
    additionalProperties: false,
    bannerComment: '',
    // Formatted below with the repository's Prettier rather than the copy this
    // package bundles, so the output does not move when that copy updates.
    format: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
  });
} catch (error) {
  fail(`${schemaPath}: ${error.message}`);
}

types = await prettier.format([...BANNER, types].join('\n'), {
  ...(await prettier.resolveConfig(typesPath)),
  parser: 'typescript',
});

// Pydantic, generated into services/brain rather than into a second Python
// distribution here. The brain is the only Python consumer, so a distribution
// would buy nothing and cost an editable install in every workflow that runs
// Python. Generating into it also gets the models type-checked by its mypy run.
const workDirectory = mkdtempSync(join(tmpdir(), 'ir-pydantic-'));
let models;
try {
  const generated = join(workDirectory, 'models.py');
  execFileSync(
    'uv',
    [
      'run',
      '--quiet',
      '--project',
      'services/brain',
      '--extra',
      'dev',
      'datamodel-codegen',
      '--input',
      schemaPath,
      '--input-file-type',
      'jsonschema',
      '--output',
      generated,
      '--output-model-type',
      'pydantic_v2.BaseModel',
      '--target-python-version',
      '3.12',
      // The wire format is the camelCase JSON the canvas sends; the brain's own
      // code reads PEP 8. An alias per field keeps both accepted.
      '--snake-case-field',
      '--allow-population-by-field-name',
      '--use-annotated',
      '--use-union-operator',
      '--use-standard-collections',
      '--use-default',
      '--field-constraints',
      '--collapse-root-models',
      // Literals rather than generated enum classes, so `kind` can discriminate
      // the node union and the Python spelling matches the TypeScript one.
      '--enum-field-as-literal',
      'all',
      // Without this the header carries the generation time, and every
      // regeneration is a diff.
      '--disable-timestamp',
      // No Black, no isort. Ruff formats the result below, and running two
      // formatters over one file is how a generator starts disagreeing with
      // the repository about where a line break goes.
      '--formatters',
      'builtin',
    ],
    { cwd: repoRoot, stdio: ['ignore', 'inherit', 'inherit'] }
  );

  const body = readFileSync(generated, 'utf8')
    .split('\n')
    // datamodel-code-generator writes its own provenance header. Ours names the
    // schema and the command, which is what a reader actually needs.
    .filter((line) => !line.startsWith('#   filename:') && !line.startsWith('# generated by'))
    .join('\n')
    .trimStart();

  writeFileSync(generated, [...PYTHON_BANNER, body].join('\n'));

  // Gate 2 runs `ruff format --check`, so the generator has to emit what Ruff
  // would produce. The brain's own pinned Ruff is used rather than an ad-hoc
  // one, so the formatter here and the formatter in CI cannot be two versions.
  execFileSync(
    'uv',
    [
      'run',
      '--quiet',
      '--project',
      'services/brain',
      '--extra',
      'dev',
      'ruff',
      'format',
      // The file is still in a temporary directory, so Ruff would not find the
      // brain's configuration by walking up from it, and would fall back to a
      // line length CI does not check against.
      '--config',
      'services/brain/pyproject.toml',
      generated,
    ],
    { cwd: repoRoot, stdio: ['ignore', 'ignore', 'inherit'] }
  );
  models = readFileSync(generated, 'utf8');
} catch (error) {
  fail(`${schemaPath}: datamodel-codegen failed: ${error.message}`);
} finally {
  rmSync(workDirectory, { recursive: true, force: true });
}

for (const [path, contents] of [
  [versionModulePath, versionModule],
  [typesPath, types],
  [pydanticPath, models],
]) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  console.log(`wrote ${relative(path)}`);
}
