#!/usr/bin/env node
/**
 * Regenerates everything derived from the IR schema.
 *
 * Gate 4's `schema-drift` job runs this and then `git diff --exit-code`, so the
 * output must be deterministic: same schema in, byte-identical files out.
 *
 *   pnpm --filter @infracanvas/ir-schema generate
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = join(packageRoot, 'schema', 'architecture-ir.schema.json');
const versionPath = join(packageRoot, 'VERSION');

const BANNER = [
  '// AUTOGENERATED FROM packages/ir-schema/schema/architecture-ir.schema.json - DO NOT EDIT',
  '// Regenerate with: pnpm --filter @infracanvas/ir-schema generate',
  '',
];

function fail(message) {
  console.error(message);
  process.exit(1);
}

function readSchema() {
  let raw;
  try {
    raw = readFileSync(schemaPath, 'utf8');
  } catch (error) {
    fail(`${schemaPath}: ${error.message}`);
  }
  try {
    return JSON.parse(raw);
  } catch (error) {
    fail(`${schemaPath}: ${error.message}`);
  }
}

function write(relativePath, contents) {
  const absolute = join(packageRoot, relativePath);
  mkdirSync(dirname(absolute), { recursive: true });
  writeFileSync(absolute, contents);
  console.log(`wrote ${relativePath}`);
}

const schema = readSchema();
const version = readFileSync(versionPath, 'utf8').trim();

if (typeof schema.$id !== 'string') {
  fail(`${schemaPath}: the schema has no $id, so its version cannot be checked`);
}
if (!schema.$id.endsWith(`/${version}.json`)) {
  fail(
    `${schemaPath}: $id is ${schema.$id} but VERSION is ${version}.\n` +
      'Bump one to match the other; the $id is what consumers pin against.'
  );
}

write(
  'src/generated/ir-version.ts',
  [
    ...BANNER,
    `export const IR_VERSION = '${version}';`,
    `export const IR_SCHEMA_ID = '${schema.$id}';`,
    '',
  ].join('\n')
);
