import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

const packageRoot = join(__dirname, '..');
const repoRoot = join(packageRoot, '..', '..');
const script = join(packageRoot, 'scripts', 'generate.mjs');

const GENERATED = [
  'packages/ir-schema/src/generated/ir-version.ts',
  'packages/ir-schema/src/generated/types.ts',
  'services/brain/src/brain/ir/models.py',
];

function run(args: string[] = []): { status: number; stderr: string } {
  try {
    execFileSync('node', [script, ...args], { encoding: 'utf8', stdio: 'pipe' });
    return { status: 0, stderr: '' };
  } catch (error) {
    const failure = error as { status: number; stderr: string };
    return { status: failure.status, stderr: failure.stderr };
  }
}

describe('the generator', () => {
  it('every generated file carries the do not edit header', () => {
    for (const path of GENERATED) {
      const head = readFileSync(join(repoRoot, path), 'utf8').split('\n').slice(0, 2).join('\n');
      expect(head, path).toContain(
        'AUTOGENERATED FROM packages/ir-schema/schema/architecture-ir.schema.json - DO NOT EDIT'
      );
      expect(head, path).toContain(
        'Regenerate with: pnpm --filter @infracanvas/ir-schema generate'
      );
    }
  });

  it('regenerating from an unchanged schema produces no diff', () => {
    const before = GENERATED.map((path) => readFileSync(join(repoRoot, path), 'utf8'));
    expect(run().status).toBe(0);
    const after = GENERATED.map((path) => readFileSync(join(repoRoot, path), 'utf8'));
    expect(after).toEqual(before);
  });

  it('exits non zero naming the schema when it is not valid json', () => {
    const directory = mkdtempSync(join(tmpdir(), 'ir-broken-'));
    const broken = join(directory, 'broken.schema.json');
    writeFileSync(broken, '{ "type": "object", ');
    try {
      const result = run(['--schema', broken]);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain(broken);
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });

  it('refuses a schema whose id disagrees with the version file', () => {
    const directory = mkdtempSync(join(tmpdir(), 'ir-mismatched-'));
    const mismatched = join(directory, 'mismatched.schema.json');
    const schema = JSON.parse(
      readFileSync(join(packageRoot, 'schema', 'architecture-ir.schema.json'), 'utf8')
    );
    schema.$id = 'https://infracanvas.dev/schema/architecture-ir/9.9.9.json';
    writeFileSync(mismatched, JSON.stringify(schema));
    try {
      const result = run(['--schema', mismatched]);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain('VERSION');
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });

  it('leaves the committed files untouched when generation fails', () => {
    const before = GENERATED.map((path) => readFileSync(join(repoRoot, path), 'utf8'));
    const directory = mkdtempSync(join(tmpdir(), 'ir-broken-'));
    const broken = join(directory, 'broken.schema.json');
    writeFileSync(broken, 'not json at all');
    try {
      expect(run(['--schema', broken]).status).toBe(1);
      expect(GENERATED.map((path) => readFileSync(join(repoRoot, path), 'utf8'))).toEqual(before);
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });
});
