/**
 * Icons for catalog services.
 *
 * One map, shared by the palette and the canvas node. They previously kept
 * separate copies, and the canvas one indexed it by `serviceId` rather than by
 * the icon name the catalog declares -- so every node on the canvas fell through
 * to the same default server glyph regardless of what it was.
 */
import {
  Activity,
  ArrowRightLeft,
  AudioLines,
  BadgeCheck,
  BarChart3,
  Bell,
  Binary,
  Bot,
  Box,
  Boxes,
  Brain,
  CalendarClock,
  Columns3,
  Cpu,
  Database,
  FileJson,
  FileText,
  GitBranch,
  GitCompare,
  GitFork,
  GitMerge,
  Globe,
  HardDrive,
  Hexagon,
  Image,
  Inbox,
  KeyRound,
  Languages,
  Layers,
  LayoutGrid,
  Library,
  ListChecks,
  Lock,
  Mail,
  Mic,
  Network,
  Package,
  Plug,
  Radio,
  Rocket,
  ScanText,
  Search,
  Server,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Table,
  Terminal,
  Users,
  Waves,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-right-left': ArrowRightLeft,
  'audio-lines': AudioLines,
  'badge-check': BadgeCheck,
  'bar-chart-3': BarChart3,
  bell: Bell,
  binary: Binary,
  bot: Bot,
  boxes: Boxes,
  brain: Brain,
  'calendar-clock': CalendarClock,
  'columns-3': Columns3,
  container: Box,
  cpu: Cpu,
  database: Database,
  'file-json': FileJson,
  'file-text': FileText,
  'git-branch': GitBranch,
  'git-compare': GitCompare,
  'git-fork': GitFork,
  'git-merge': GitMerge,
  globe: Globe,
  'hard-drive': HardDrive,
  hexagon: Hexagon,
  image: Image,
  inbox: Inbox,
  'key-round': KeyRound,
  languages: Languages,
  layers: Layers,
  'layout-grid': LayoutGrid,
  library: Library,
  'list-checks': ListChecks,
  lock: Lock,
  mail: Mail,
  mic: Mic,
  network: Network,
  package: Package,
  plug: Plug,
  radio: Radio,
  rocket: Rocket,
  'scan-text': ScanText,
  search: Search,
  server: Server,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  table: Table,
  terminal: Terminal,
  users: Users,
  waves: Waves,
  zap: Zap,
};

/** The icon a service declares, falling back to a generic one. */
export function iconFor(iconName: string | undefined): LucideIcon {
  return (iconName && ICONS[iconName]) || Server;
}
