// Pulumi Code Generator for InfraCanvas

import type { ServiceNodeData, PulumiLanguage } from '../types';

export interface PulumiFile {
  path: string;
  content: string;
}

export interface PulumiProject {
  files: PulumiFile[];
}

interface Node<T> {
  id: string;
  data: T;
  position: { x: number; y: number };
  parentNode?: string;
}

interface Edge {
  id: string;
  source: string;
  target: string;
}

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_');
}

function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
}

export function generatePulumiProject(
  nodes: Node<ServiceNodeData>[],
  edges: Edge[],
  language: PulumiLanguage = 'typescript'
): PulumiProject {
  const files: PulumiFile[] = [];

  if (nodes.length === 0) {
    if (language === 'typescript') {
      files.push({
        path: 'index.ts',
        content: `// No resources to generate\n// Drag AWS services onto the canvas to create your architecture\n`,
      });
    } else {
      files.push({
        path: '__main__.py',
        content: `# No resources to generate\n# Drag AWS services onto the canvas to create your architecture\n`,
      });
    }
    return { files };
  }

  if (language === 'typescript') {
    files.push({ path: 'index.ts', content: generateIndexTs(nodes, edges) });
    files.push({ path: 'Pulumi.yaml', content: generatePulumiYaml('typescript') });
    files.push({ path: 'package.json', content: generatePackageJson() });
    files.push({ path: 'tsconfig.json', content: generateTsConfig() });
  } else {
    files.push({ path: '__main__.py', content: generateMainPy(nodes, edges) });
    files.push({ path: 'Pulumi.yaml', content: generatePulumiYaml('python') });
    files.push({ path: 'requirements.txt', content: generateRequirements() });
  }

  files.push({ path: 'README.md', content: generateReadme(nodes, language) });

  return { files };
}

export function generatePulumi(
  nodes: Node<ServiceNodeData>[],
  edges: Edge[],
  language: PulumiLanguage = 'typescript'
): string {
  const project = generatePulumiProject(nodes, edges, language);
  return project.files.map((f) => `# === ${f.path} ===\n${f.content}`).join('\n\n');
}

function generateIndexTs(nodes: Node<ServiceNodeData>[], _edges: Edge[]): string {
  const imports = new Set<string>();
  imports.add('import * as pulumi from "@pulumi/pulumi";');
  imports.add('import * as aws from "@pulumi/aws";');

  let content = `// Generated by InfraCanvas
${Array.from(imports).join('\n')}

const config = new pulumi.Config();
const environment = config.get("environment") || "production";
const projectName = config.get("projectName") || "infracanvas-project";

const tags = {
  Environment: environment,
  ManagedBy: "Pulumi",
  Project: projectName,
};

`;

  nodes.forEach((node) => {
    const varName = toCamelCase(sanitizeName(node.data.serviceName));
    content += generateTypeScriptResource(node, varName);
  });

  content += `\n// Exports\n`;
  nodes.forEach((node) => {
    const varName = toCamelCase(sanitizeName(node.data.serviceName));
    content += `export const ${varName}Id = ${varName}.id;\n`;
  });

  return content;
}

function generateTypeScriptResource(node: Node<ServiceNodeData>, varName: string): string {
  const serviceId = node.data.serviceId;
  const props = node.data.properties;

  switch (serviceId) {
    case 'ec2':
      return `
// EC2 Instance: ${node.data.serviceName}
const ${varName} = new aws.ec2.Instance("${varName}", {
  instanceType: "${props.instanceType || 't3.micro'}",
  ami: aws.ec2.getAmi({
    mostRecent: true,
    owners: ["amazon"],
    filters: [{ name: "name", values: ["al2023-ami-*-x86_64"] }],
  }).then(ami => ami.id),
  rootBlockDevice: {
    volumeSize: ${props.rootVolumeSize || 30},
    volumeType: "${props.rootVolumeType || 'gp3'}",
    encrypted: true,
  },
  associatePublicIpAddress: ${props.publicIp ?? true},
  tags: { ...tags, Name: "${props.instanceName || varName}" },
});

`;

    case 'lambda':
      return `
// Lambda Function: ${node.data.serviceName}
const ${varName}Role = new aws.iam.Role("${varName}Role", {
  assumeRolePolicy: JSON.stringify({
    Version: "2012-10-17",
    Statement: [{
      Action: "sts:AssumeRole",
      Effect: "Allow",
      Principal: { Service: "lambda.amazonaws.com" },
    }],
  }),
});

new aws.iam.RolePolicyAttachment("${varName}BasicExecution", {
  role: ${varName}Role.name,
  policyArn: "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
});

const ${varName} = new aws.lambda.Function("${varName}", {
  name: "${props.functionName || varName}",
  role: ${varName}Role.arn,
  runtime: "${props.runtime || 'nodejs20.x'}",
  handler: "${props.handler || 'index.handler'}",
  memorySize: ${props.memory || 256},
  timeout: ${props.timeout || 30},
  architectures: ["${props.architecture || 'arm64'}"],
  code: new pulumi.asset.AssetArchive({
    "index.js": new pulumi.asset.StringAsset("exports.handler = async () => ({ statusCode: 200 });"),
  }),
  tags: { ...tags, Name: "${props.functionName || varName}" },
});

`;

    case 's3':
      return `
// S3 Bucket: ${node.data.serviceName}
const ${varName} = new aws.s3.Bucket("${varName}", {
  bucket: "${props.bucketName || varName}",
  tags: { ...tags, Name: "${props.bucketName || varName}" },
});

new aws.s3.BucketVersioningV2("${varName}Versioning", {
  bucket: ${varName}.id,
  versioningConfiguration: {
    status: ${props.versioning ? '"Enabled"' : '"Suspended"'},
  },
});

new aws.s3.BucketPublicAccessBlock("${varName}PublicAccess", {
  bucket: ${varName}.id,
  blockPublicAcls: ${props.publicAccess ?? true},
  blockPublicPolicy: ${props.publicAccess ?? true},
  ignorePublicAcls: ${props.publicAccess ?? true},
  restrictPublicBuckets: ${props.publicAccess ?? true},
});

`;

    case 'rds':
      return `
// RDS Database: ${node.data.serviceName}
const ${varName} = new aws.rds.Instance("${varName}", {
  identifier: "${props.identifier || varName}",
  engine: "${props.engine || 'postgres'}",
  engineVersion: "${props.engine === 'mysql' ? '8.0' : '16'}",
  instanceClass: "${props.instanceClass || 'db.t3.micro'}",
  allocatedStorage: ${props.allocatedStorage || 20},
  storageType: "gp3",
  storageEncrypted: true,
  multiAz: ${props.multiAz ?? false},
  publiclyAccessible: ${props.publiclyAccessible ?? false},
  deletionProtection: ${props.deletionProtection ?? true},
  skipFinalSnapshot: true,
  tags: { ...tags, Name: "${props.identifier || varName}" },
});

`;

    case 'dynamodb':
      return `
// DynamoDB Table: ${node.data.serviceName}
const ${varName} = new aws.dynamodb.Table("${varName}", {
  name: "${props.tableName || varName}",
  billingMode: "${props.billingMode || 'PAY_PER_REQUEST'}",
  hashKey: "${props.hashKey || 'id'}",
  attributes: [{
    name: "${props.hashKey || 'id'}",
    type: "${props.hashKeyType || 'S'}",
  }],
  pointInTimeRecovery: {
    enabled: ${props.pointInTimeRecovery ?? false},
  },
  tags: { ...tags, Name: "${props.tableName || varName}" },
});

`;

    case 'api-gateway':
      return `
// API Gateway: ${node.data.serviceName}
const ${varName} = new aws.apigatewayv2.Api("${varName}", {
  name: "${props.apiName || varName}",
  protocolType: "${props.apiType || 'HTTP'}",
  corsConfiguration: {
    allowOrigins: ${JSON.stringify(String(props.corsOrigins || '*').split(','))},
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allowHeaders: ["*"],
  },
  tags: { ...tags, Name: "${props.apiName || varName}" },
});

new aws.apigatewayv2.Stage("${varName}Stage", {
  apiId: ${varName}.id,
  name: "${props.stageName || 'prod'}",
  autoDeploy: true,
});

`;

    case 'sqs':
      return `
// SQS Queue: ${node.data.serviceName}
const ${varName} = new aws.sqs.Queue("${varName}", {
  name: "${props.queueName || varName}",
  fifoQueue: ${props.fifoQueue ?? false},
  visibilityTimeoutSeconds: ${props.visibilityTimeout || 30},
  messageRetentionSeconds: ${props.messageRetention || 345600},
  sqsManagedSseEnabled: ${props.enableEncryption ?? true},
  tags: { ...tags, Name: "${props.queueName || varName}" },
});

`;

    case 'sns':
      return `
// SNS Topic: ${node.data.serviceName}
const ${varName} = new aws.sns.Topic("${varName}", {
  name: "${props.topicName || varName}",
  displayName: "${props.displayName || ''}",
  fifoTopic: ${props.fifoTopic ?? false},
  tags: { ...tags, Name: "${props.topicName || varName}" },
});

`;

    case 'cognito':
      return `
// Cognito User Pool: ${node.data.serviceName}
const ${varName} = new aws.cognito.UserPool("${varName}", {
  name: "${props.poolName || varName}",
  mfaConfiguration: "${props.mfaConfiguration || 'OPTIONAL'}",
  passwordPolicy: {
    minimumLength: ${props.passwordMinLength || 8},
    requireLowercase: true,
    requireNumbers: true,
    requireSymbols: true,
    requireUppercase: true,
  },
  tags: { ...tags, Name: "${props.poolName || varName}" },
});

`;

    case 'cloudfront':
      return `
// CloudFront Distribution: ${node.data.serviceName}
const ${varName} = new aws.cloudfront.Distribution("${varName}", {
  enabled: true,
  comment: "${props.comment || 'My Distribution'}",
  defaultRootObject: "${props.defaultRootObject || 'index.html'}",
  priceClass: "${props.priceClass || 'PriceClass_100'}",
  origins: [{
    domainName: "placeholder.s3.amazonaws.com",
    originId: "S3Origin",
  }],
  defaultCacheBehavior: {
    allowedMethods: ["GET", "HEAD"],
    cachedMethods: ["GET", "HEAD"],
    targetOriginId: "S3Origin",
    viewerProtocolPolicy: "${props.viewerProtocol || 'redirect-to-https'}",
    compress: ${props.enableCompression ?? true},
    forwardedValues: {
      queryString: false,
      cookies: { forward: "none" },
    },
  },
  restrictions: {
    geoRestriction: { restrictionType: "none" },
  },
  viewerCertificate: {
    cloudfrontDefaultCertificate: true,
  },
  tags: { ...tags, Name: "${props.comment || varName}" },
});

`;

    default:
      return `// TODO: Add ${serviceId} resource\n`;
  }
}

function generateMainPy(nodes: Node<ServiceNodeData>[], _edges: Edge[]): string {
  let content = `"""Generated by InfraCanvas"""
import pulumi
import pulumi_aws as aws

config = pulumi.Config()
environment = config.get("environment") or "production"
project_name = config.get("projectName") or "infracanvas-project"

tags = {
    "Environment": environment,
    "ManagedBy": "Pulumi",
    "Project": project_name,
}

`;

  nodes.forEach((node) => {
    const varName = sanitizeName(node.data.serviceName);
    content += generatePythonResource(node, varName);
  });

  content += `\n# Exports\n`;
  nodes.forEach((node) => {
    const varName = sanitizeName(node.data.serviceName);
    content += `pulumi.export("${varName}_id", ${varName}.id)\n`;
  });

  return content;
}

function generatePythonResource(node: Node<ServiceNodeData>, varName: string): string {
  const serviceId = node.data.serviceId;
  const props = node.data.properties;

  switch (serviceId) {
    case 'ec2':
      return `
# EC2 Instance: ${node.data.serviceName}
${varName} = aws.ec2.Instance("${varName}",
    instance_type="${props.instanceType || 't3.micro'}",
    root_block_device=aws.ec2.InstanceRootBlockDeviceArgs(
        volume_size=${props.rootVolumeSize || 30},
        volume_type="${props.rootVolumeType || 'gp3'}",
        encrypted=True,
    ),
    associate_public_ip_address=${props.publicIp ? 'True' : 'False'},
    tags={**tags, "Name": "${props.instanceName || varName}"},
)

`;

    case 'lambda':
      return `
# Lambda Function: ${node.data.serviceName}
${varName}_role = aws.iam.Role("${varName}Role",
    assume_role_policy="""{
        "Version": "2012-10-17",
        "Statement": [{
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {"Service": "lambda.amazonaws.com"}
        }]
    }""",
)

aws.iam.RolePolicyAttachment("${varName}BasicExecution",
    role=${varName}_role.name,
    policy_arn="arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
)

${varName} = aws.lambda_.Function("${varName}",
    name="${props.functionName || varName}",
    role=${varName}_role.arn,
    runtime="${props.runtime || 'nodejs20.x'}",
    handler="${props.handler || 'index.handler'}",
    memory_size=${props.memory || 256},
    timeout=${props.timeout || 30},
    code=pulumi.AssetArchive({
        "index.js": pulumi.StringAsset("exports.handler = async () => ({ statusCode: 200 });"),
    }),
    tags={**tags, "Name": "${props.functionName || varName}"},
)

`;

    case 's3':
      return `
# S3 Bucket: ${node.data.serviceName}
${varName} = aws.s3.Bucket("${varName}",
    bucket="${props.bucketName || varName}",
    tags={**tags, "Name": "${props.bucketName || varName}"},
)

aws.s3.BucketVersioningV2("${varName}Versioning",
    bucket=${varName}.id,
    versioning_configuration=aws.s3.BucketVersioningV2VersioningConfigurationArgs(
        status="${props.versioning ? 'Enabled' : 'Suspended'}",
    ),
)

aws.s3.BucketPublicAccessBlock("${varName}PublicAccess",
    bucket=${varName}.id,
    block_public_acls=${props.publicAccess ? 'True' : 'False'},
    block_public_policy=${props.publicAccess ? 'True' : 'False'},
    ignore_public_acls=${props.publicAccess ? 'True' : 'False'},
    restrict_public_buckets=${props.publicAccess ? 'True' : 'False'},
)

`;

    case 'dynamodb':
      return `
# DynamoDB Table: ${node.data.serviceName}
${varName} = aws.dynamodb.Table("${varName}",
    name="${props.tableName || varName}",
    billing_mode="${props.billingMode || 'PAY_PER_REQUEST'}",
    hash_key="${props.hashKey || 'id'}",
    attributes=[aws.dynamodb.TableAttributeArgs(
        name="${props.hashKey || 'id'}",
        type="${props.hashKeyType || 'S'}",
    )],
    tags={**tags, "Name": "${props.tableName || varName}"},
)

`;

    case 'sqs':
      return `
# SQS Queue: ${node.data.serviceName}
${varName} = aws.sqs.Queue("${varName}",
    name="${props.queueName || varName}",
    fifo_queue=${props.fifoQueue ? 'True' : 'False'},
    visibility_timeout_seconds=${props.visibilityTimeout || 30},
    message_retention_seconds=${props.messageRetention || 345600},
    sqs_managed_sse_enabled=${props.enableEncryption ? 'True' : 'False'},
    tags={**tags, "Name": "${props.queueName || varName}"},
)

`;

    case 'sns':
      return `
# SNS Topic: ${node.data.serviceName}
${varName} = aws.sns.Topic("${varName}",
    name="${props.topicName || varName}",
    display_name="${props.displayName || ''}",
    fifo_topic=${props.fifoTopic ? 'True' : 'False'},
    tags={**tags, "Name": "${props.topicName || varName}"},
)

`;

    default:
      return `# TODO: Add ${serviceId} resource\n`;
  }
}

function generatePulumiYaml(language: PulumiLanguage): string {
  if (language === 'typescript') {
    return `name: infracanvas-project
runtime: nodejs
description: Infrastructure generated by InfraCanvas
`;
  }
  return `name: infracanvas-project
runtime: python
description: Infrastructure generated by InfraCanvas
`;
}

function generatePackageJson(): string {
  return `{
  "name": "infracanvas-project",
  "devDependencies": {
    "@types/node": "^18"
  },
  "dependencies": {
    "@pulumi/pulumi": "^3.0.0",
    "@pulumi/aws": "^6.0.0"
  }
}
`;
}

function generateTsConfig(): string {
  return `{
  "compilerOptions": {
    "strict": true,
    "outDir": "bin",
    "target": "es2020",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "experimentalDecorators": true,
    "pretty": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "forceConsistentCasingInFileNames": true
  },
  "files": ["index.ts"]
}
`;
}

function generateRequirements(): string {
  return `pulumi>=3.0.0,<4.0.0
pulumi-aws>=6.0.0,<7.0.0
`;
}

function generateReadme(nodes: Node<ServiceNodeData>[], language: PulumiLanguage): string {
  const serviceTypes = [...new Set(nodes.map((n) => n.data.serviceId))];

  return `# Infrastructure as Code

Generated by [InfraCanvas](https://github.com/johnbekele/infracanvas)

## Resources

This project includes the following AWS resources:

${serviceTypes.map((s) => `- ${s}`).join('\n')}

## Usage

1. Configure AWS credentials
2. Run \`pulumi login\`
3. Run \`pulumi up\`

## Language

This project uses **${language === 'typescript' ? 'TypeScript' : 'Python'}**.
`;
}
