// Terraform Code Generator for InfraCanvas

import { getServiceById } from '../aws-services';
import type { ServiceNodeData } from '../types';

export interface TerraformFile {
  path: string;
  content: string;
}

export interface TerraformProject {
  files: TerraformFile[];
}

interface Node<T> {
  id: string;
  data: T;
  position: { x: number; y: number };
  parentNode?: string;
}

interface Edge {
  id: string;
  source: string;
  target: string;
}

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_');
}

export function generateTerraformProject(
  nodes: Node<ServiceNodeData>[],
  _edges: Edge[]
): TerraformProject {
  const files: TerraformFile[] = [];

  if (nodes.length === 0) {
    files.push({
      path: 'main.tf',
      content: `# No resources to generate\n# Drag AWS services onto the canvas to create your architecture`,
    });
    return { files };
  }

  files.push({ path: 'main.tf', content: generateMainTf(nodes) });
  files.push({ path: 'variables.tf', content: generateVariablesTf() });
  files.push({ path: 'outputs.tf', content: generateOutputsTf(nodes) });

  const serviceTypes = new Set(nodes.map((n) => n.data.serviceId));
  serviceTypes.forEach((serviceId) => {
    const serviceNodes = nodes.filter((n) => n.data.serviceId === serviceId);
    const moduleFiles = generateServiceModule(serviceId, serviceNodes);
    files.push(...moduleFiles);
  });

  files.push({ path: 'README.md', content: generateReadme(nodes) });

  return { files };
}

export function generateTerraform(nodes: Node<ServiceNodeData>[], edges: Edge[]): string {
  const project = generateTerraformProject(nodes, edges);
  return project.files.map((f) => `# === ${f.path} ===\n${f.content}`).join('\n\n');
}

function generateMainTf(nodes: Node<ServiceNodeData>[]): string {
  const serviceTypes = new Set(nodes.map((n) => n.data.serviceId));

  let content = `# Generated by InfraCanvas
# Main Terraform Configuration

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Environment = var.environment
      ManagedBy   = "Terraform"
      Project     = var.project_name
    }
  }
}

# Module Instances
`;

  serviceTypes.forEach((serviceId) => {
    const serviceNodes = nodes.filter((n) => n.data.serviceId === serviceId);
    serviceNodes.forEach((node) => {
      const resourceName = sanitizeName(node.data.serviceName);
      content += `
module "${resourceName}" {
  source = "./modules/${serviceId}"

  name        = "${resourceName}"
  environment = var.environment
${generateModuleInputs(node)}
}
`;
    });
  });

  return content;
}

function generateModuleInputs(node: Node<ServiceNodeData>): string {
  const props = node.data.properties;
  const lines: string[] = [];

  Object.entries(props).forEach(([key, value]) => {
    if (value !== '' && value !== undefined && value !== null) {
      if (typeof value === 'string') {
        lines.push(`  ${key} = "${value}"`);
      } else if (typeof value === 'boolean') {
        lines.push(`  ${key} = ${value}`);
      } else if (typeof value === 'number') {
        lines.push(`  ${key} = ${value}`);
      }
    }
  });

  return lines.join('\n');
}

function generateVariablesTf(): string {
  return `# Generated by InfraCanvas
# Input Variables

variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (e.g., dev, staging, prod)"
  type        = string
  default     = "production"
}

variable "project_name" {
  description = "Project name for tagging"
  type        = string
  default     = "infracanvas-project"
}
`;
}

function generateOutputsTf(nodes: Node<ServiceNodeData>[]): string {
  let content = `# Generated by InfraCanvas\n# Outputs\n\n`;

  nodes.forEach((node) => {
    const resourceName = sanitizeName(node.data.serviceName);
    content += `output "${resourceName}_id" {
  description = "ID of ${node.data.serviceName}"
  value       = module.${resourceName}.id
}

`;
  });

  return content;
}

function generateServiceModule(
  serviceId: string,
  _nodes: Node<ServiceNodeData>[]
): TerraformFile[] {
  const files: TerraformFile[] = [];

  files.push({
    path: `modules/${serviceId}/main.tf`,
    content: generateModuleMain(serviceId),
  });

  files.push({
    path: `modules/${serviceId}/variables.tf`,
    content: generateModuleVariables(serviceId),
  });

  files.push({
    path: `modules/${serviceId}/outputs.tf`,
    content: generateModuleOutputs(serviceId),
  });

  return files;
}

function generateModuleMain(serviceId: string): string {
  const generators: Record<string, () => string> = {
    ec2: generateEC2Module,
    lambda: generateLambdaModule,
    s3: generateS3Module,
    rds: generateRDSModule,
    dynamodb: generateDynamoDBModule,
    'api-gateway': generateAPIGatewayModule,
    cloudfront: generateCloudFrontModule,
    sqs: generateSQSModule,
    sns: generateSNSModule,
    cognito: generateCognitoModule,
    vpc: generateVPCModule,
    ecs: generateECSModule,
    elasticache: generateElastiCacheModule,
    iam: generateIAMModule,
    route53: generateRoute53Module,
    'vpc-environment': generateVpcEnvironmentModule,
    'public-subnet': generateSubnetModule,
    'private-subnet': generateSubnetModule,
    alb: generateALBModule,
    nlb: generateNLBModule,
    'nat-gateway': generateNatGatewayModule,
  };

  return generators[serviceId]?.() || `# TODO: Add ${serviceId} module configuration\n`;
}

function generateEC2Module(): string {
  return `# EC2 Instance Module

data "aws_ami" "selected" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}

resource "aws_instance" "this" {
  ami           = data.aws_ami.selected.id
  instance_type = var.instanceType

  root_block_device {
    volume_size = var.rootVolumeSize
    volume_type = var.rootVolumeType
    encrypted   = true
  }

  associate_public_ip_address = var.publicIp
  key_name                    = var.keyPair != "" ? var.keyPair : null
  monitoring                  = var.monitoring

  tags = {
    Name = var.instanceName
  }
}
`;
}

function generateLambdaModule(): string {
  return `# Lambda Function Module

resource "aws_iam_role" "lambda" {
  name = "\${var.name}_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_lambda_function" "this" {
  filename         = "\${path.module}/lambda_placeholder.zip"
  function_name    = var.functionName
  role             = aws_iam_role.lambda.arn
  handler          = var.handler
  runtime          = var.runtime
  memory_size      = var.memory
  timeout          = var.timeout
  architectures    = [var.architecture]

  tags = {
    Name = var.name
  }
}
`;
}

function generateS3Module(): string {
  return `# S3 Bucket Module

resource "aws_s3_bucket" "this" {
  bucket = var.bucketName

  tags = {
    Name = var.name
  }
}

resource "aws_s3_bucket_versioning" "this" {
  bucket = aws_s3_bucket.this.id

  versioning_configuration {
    status = var.versioning ? "Enabled" : "Suspended"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  count  = var.encryption != "none" ? 1 : 0
  bucket = aws_s3_bucket.this.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = var.encryption == "aws:kms" ? "aws:kms" : "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  bucket = aws_s3_bucket.this.id

  block_public_acls       = var.publicAccess
  block_public_policy     = var.publicAccess
  ignore_public_acls      = var.publicAccess
  restrict_public_buckets = var.publicAccess
}
`;
}

function generateRDSModule(): string {
  return `# RDS Database Module

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = var.engine
  engine_version = var.engine == "postgres" ? "16" : "8.0"

  instance_class        = var.instanceClass
  allocated_storage     = var.allocatedStorage
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = "mydb"
  username = "admin"
  password = var.password

  multi_az               = var.multiAz
  publicly_accessible    = var.publiclyAccessible
  deletion_protection    = var.deletionProtection
  skip_final_snapshot    = true

  tags = {
    Name = var.name
  }
}
`;
}

function generateDynamoDBModule(): string {
  return `# DynamoDB Table Module

resource "aws_dynamodb_table" "this" {
  name           = var.tableName
  billing_mode   = var.billingMode
  hash_key       = var.hashKey

  attribute {
    name = var.hashKey
    type = var.hashKeyType
  }

  point_in_time_recovery {
    enabled = var.pointInTimeRecovery
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateAPIGatewayModule(): string {
  return `# API Gateway Module

resource "aws_apigatewayv2_api" "this" {
  name          = var.apiName
  protocol_type = var.apiType

  cors_configuration {
    allow_origins = split(",", var.corsOrigins)
    allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers = ["*"]
  }

  tags = {
    Name = var.name
  }
}

resource "aws_apigatewayv2_stage" "this" {
  api_id      = aws_apigatewayv2_api.this.id
  name        = var.stageName
  auto_deploy = true
}
`;
}

function generateCloudFrontModule(): string {
  return `# CloudFront Distribution Module

resource "aws_cloudfront_distribution" "this" {
  enabled             = true
  comment             = var.comment
  default_root_object = var.defaultRootObject
  price_class         = var.priceClass

  origin {
    domain_name = "placeholder.s3.amazonaws.com"
    origin_id   = "S3Origin"
  }

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3Origin"
    viewer_protocol_policy = var.viewerProtocol
    compress               = var.enableCompression

    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateSQSModule(): string {
  return `# SQS Queue Module

resource "aws_sqs_queue" "this" {
  name                       = var.queueName
  fifo_queue                 = var.fifoQueue
  visibility_timeout_seconds = var.visibilityTimeout
  message_retention_seconds  = var.messageRetention
  sqs_managed_sse_enabled    = var.enableEncryption

  tags = {
    Name = var.name
  }
}
`;
}

function generateSNSModule(): string {
  return `# SNS Topic Module

resource "aws_sns_topic" "this" {
  name         = var.topicName
  display_name = var.displayName
  fifo_topic   = var.fifoTopic

  tags = {
    Name = var.name
  }
}
`;
}

function generateCognitoModule(): string {
  return `# Cognito User Pool Module

resource "aws_cognito_user_pool" "this" {
  name = var.poolName

  mfa_configuration = var.mfaConfiguration

  password_policy {
    minimum_length    = var.passwordMinLength
    require_lowercase = true
    require_numbers   = true
    require_symbols   = true
    require_uppercase = true
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateVPCModule(): string {
  return `# VPC Module

resource "aws_vpc" "this" {
  cidr_block           = var.cidrBlock
  enable_dns_hostnames = var.enableDnsHostnames
  enable_dns_support   = var.enableDnsSupport

  tags = {
    Name = var.vpcName
  }
}
`;
}

function generateECSModule(): string {
  return `# ECS Module

resource "aws_ecs_cluster" "this" {
  name = var.clusterName

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateElastiCacheModule(): string {
  return `# ElastiCache Module

resource "aws_elasticache_cluster" "this" {
  cluster_id           = var.clusterId
  engine               = var.engine
  node_type            = var.nodeType
  num_cache_nodes      = var.numCacheNodes
  port                 = var.port

  tags = {
    Name = var.name
  }
}
`;
}

function generateIAMModule(): string {
  return `# IAM Role Module

resource "aws_iam_role" "this" {
  name        = var.roleName
  description = var.description

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = var.assumeRoleService
      }
    }]
  })

  tags = {
    Name = var.name
  }
}
`;
}

function generateRoute53Module(): string {
  return `# Route 53 Module

resource "aws_route53_zone" "this" {
  name = var.domainName

  tags = {
    Name = var.name
  }
}
`;
}

function generateVpcEnvironmentModule(): string {
  return `# VPC Environment Module

resource "aws_vpc" "this" {
  cidr_block           = var.cidrBlock
  enable_dns_hostnames = var.enableDnsHostnames
  enable_dns_support   = var.enableDnsSupport

  tags = {
    Name = var.vpcName
  }
}

resource "aws_internet_gateway" "this" {
  vpc_id = aws_vpc.this.id

  tags = {
    Name = "\${var.vpcName}-igw"
  }
}
`;
}

function generateSubnetModule(): string {
  return `# Subnet Module

resource "aws_subnet" "this" {
  vpc_id            = var.vpc_id
  cidr_block        = var.cidrBlock
  availability_zone = var.availabilityZone

  tags = {
    Name = var.subnetName
  }
}
`;
}

function generateALBModule(): string {
  return `# Application Load Balancer Module

resource "aws_lb" "this" {
  name               = var.albName
  internal           = var.internal
  load_balancer_type = "application"
  idle_timeout       = var.idleTimeout
  enable_http2       = var.enableHttp2

  tags = {
    Name = var.name
  }
}
`;
}

function generateNLBModule(): string {
  return `# Network Load Balancer Module

resource "aws_lb" "this" {
  name                       = var.nlbName
  internal                   = var.internal
  load_balancer_type         = "network"
  enable_cross_zone_load_balancing = var.enableCrossZone

  tags = {
    Name = var.name
  }
}
`;
}

function generateNatGatewayModule(): string {
  return `# NAT Gateway Module

resource "aws_eip" "this" {
  domain = "vpc"

  tags = {
    Name = "\${var.natName}-eip"
  }
}

resource "aws_nat_gateway" "this" {
  allocation_id     = aws_eip.this.id
  subnet_id         = var.subnet_id
  connectivity_type = var.connectivityType

  tags = {
    Name = var.natName
  }
}
`;
}

function generateModuleVariables(serviceId: string): string {
  const service = getServiceById(serviceId);
  if (!service) return '# No variables defined\n';

  let content = `# Variables for ${service.name} module\n\n`;
  content += `variable "name" {\n  type = string\n}\n\n`;
  content += `variable "environment" {\n  type = string\n}\n\n`;

  service.properties.forEach((prop) => {
    const tfType =
      prop.type === 'boolean' ? 'bool' : prop.type === 'number' ? 'number' : 'string';
    content += `variable "${prop.name}" {\n`;
    content += `  type    = ${tfType}\n`;
    content += `  default = ${JSON.stringify(prop.default)}\n`;
    content += `}\n\n`;
  });

  return content;
}

function generateModuleOutputs(serviceId: string): string {
  return `# Outputs for ${serviceId} module

output "id" {
  description = "Resource ID"
  value       = aws_${serviceId === 'api-gateway' ? 'apigatewayv2_api' : serviceId.replace('-', '_')}.this.id
}
`;
}

function generateReadme(nodes: Node<ServiceNodeData>[]): string {
  const serviceTypes = [...new Set(nodes.map((n) => n.data.serviceId))];

  return `# Infrastructure as Code

Generated by [InfraCanvas](https://github.com/johnbekele/infracanvas)

## Resources

This project includes the following AWS resources:

${serviceTypes.map((s) => `- ${s}`).join('\n')}

## Usage

1. Configure AWS credentials
2. Run \`terraform init\`
3. Run \`terraform plan\`
4. Run \`terraform apply\`

## Customization

Each service is defined as a module in the \`modules/\` directory.
Modify the module inputs in \`main.tf\` or update the module definitions.
`;
}
