// GitOps Workflow Generator
// Generates GitHub Actions workflows for infrastructure deployment

export type IaCType = 'terraform' | 'pulumi-ts' | 'pulumi-py';

export interface WorkflowOptions {
  iacType: IaCType;
  directory: string;
  branch?: string;
  autoApply?: boolean;
  awsRegion?: string;
}

export interface GeneratedWorkflow {
  path: string;
  content: string;
}

/**
 * Generate a GitHub Actions workflow for the specified IaC type
 */
export function generateWorkflow(options: WorkflowOptions): GeneratedWorkflow {
  const {
    iacType,
    directory,
    branch = 'main',
    autoApply = false,
    awsRegion = 'us-east-1',
  } = options;

  switch (iacType) {
    case 'terraform':
      return {
        path: '.github/workflows/terraform.yml',
        content: generateTerraformWorkflow({ directory, branch, autoApply, awsRegion }),
      };
    case 'pulumi-ts':
      return {
        path: '.github/workflows/pulumi.yml',
        content: generatePulumiWorkflow({
          directory,
          branch,
          autoApply,
          awsRegion,
          language: 'typescript',
        }),
      };
    case 'pulumi-py':
      return {
        path: '.github/workflows/pulumi.yml',
        content: generatePulumiWorkflow({
          directory,
          branch,
          autoApply,
          awsRegion,
          language: 'python',
        }),
      };
  }
}

interface TerraformWorkflowOptions {
  directory: string;
  branch: string;
  autoApply: boolean;
  awsRegion: string;
}

function generateTerraformWorkflow(options: TerraformWorkflowOptions): string {
  const { directory, branch, autoApply, awsRegion } = options;

  return `# Terraform Deployment Workflow
# Generated by InfraCanvas - https://github.com/johnbekele/infracanvas

name: Deploy Infrastructure (Terraform)

on:
  push:
    branches: [${branch}]
    paths:
      - '${directory}/**'
  pull_request:
    branches: [${branch}]
    paths:
      - '${directory}/**'
  workflow_dispatch:

env:
  TF_LOG: INFO
  AWS_REGION: ${awsRegion}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${directory}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${awsRegion}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\\n\${{ steps.plan.outputs.stdout }}"
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = \`#### Terraform Format and Style \${{ steps.fmt.outcome == 'success' && '\\u2705' || '\\u274C' }}
            #### Terraform Initialization \${{ steps.init.outcome == 'success' && '\\u2705' || '\\u274C' }}
            #### Terraform Validation \${{ steps.validate.outcome == 'success' && '\\u2705' || '\\u274C' }}
            #### Terraform Plan \${{ steps.plan.outcome == 'success' && '\\u2705' || '\\u274C' }}

            <details><summary>Show Plan</summary>

            \\\`\\\`\\\`
            \${process.env.PLAN}
            \\\`\\\`\\\`

            </details>

            *Pushed by: @\${{ github.actor }}, Action: \\\`\${{ github.event_name }}\\\`*\`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
${
  autoApply
    ? `
      - name: Terraform Apply
        if: github.ref == 'refs/heads/${branch}' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
`
    : `
      # Uncomment to enable auto-apply on push to ${branch}
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/${branch}' && github.event_name == 'push'
      #   run: terraform apply -auto-approve -input=false
`
}
`;
}

interface PulumiWorkflowOptions {
  directory: string;
  branch: string;
  autoApply: boolean;
  awsRegion: string;
  language: 'typescript' | 'python';
}

function generatePulumiWorkflow(options: PulumiWorkflowOptions): string {
  const { directory, branch, autoApply, awsRegion, language } = options;

  const setupSteps =
    language === 'typescript'
      ? `
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${directory}/package-lock.json

      - name: Install Dependencies
        working-directory: ${directory}
        run: npm ci`
      : `
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ${directory}/requirements.txt

      - name: Install Dependencies
        working-directory: ${directory}
        run: pip install -r requirements.txt`;

  return `# Pulumi Deployment Workflow
# Generated by InfraCanvas - https://github.com/johnbekele/infracanvas

name: Deploy Infrastructure (Pulumi)

on:
  push:
    branches: [${branch}]
    paths:
      - '${directory}/**'
  pull_request:
    branches: [${branch}]
    paths:
      - '${directory}/**'
  workflow_dispatch:

env:
  PULUMI_ACCESS_TOKEN: \${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_REGION: ${awsRegion}

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${awsRegion}
${setupSteps}

      - name: Setup Pulumi
        uses: pulumi/actions@v5

      - name: Pulumi Preview
        if: github.event_name == 'pull_request'
        uses: pulumi/actions@v5
        with:
          command: preview
          work-dir: ${directory}
          stack-name: dev
          comment-on-pr: true
          github-token: \${{ secrets.GITHUB_TOKEN }}
${
  autoApply
    ? `
      - name: Pulumi Up
        if: github.ref == 'refs/heads/${branch}' && github.event_name == 'push'
        uses: pulumi/actions@v5
        with:
          command: up
          work-dir: ${directory}
          stack-name: dev
`
    : `
      # Uncomment to enable auto-deploy on push to ${branch}
      # - name: Pulumi Up
      #   if: github.ref == 'refs/heads/${branch}' && github.event_name == 'push'
      #   uses: pulumi/actions@v5
      #   with:
      #     command: up
      #     work-dir: ${directory}
      #     stack-name: dev
`
}
`;
}

/**
 * Generate a README with setup instructions for the workflow
 */
export function generateWorkflowReadme(iacType: IaCType): string {
  const secrets =
    iacType === 'terraform'
      ? `
| Secret | Description |
|--------|-------------|
| \`AWS_ACCESS_KEY_ID\` | Your AWS access key ID |
| \`AWS_SECRET_ACCESS_KEY\` | Your AWS secret access key |
`
      : `
| Secret | Description |
|--------|-------------|
| \`AWS_ACCESS_KEY_ID\` | Your AWS access key ID |
| \`AWS_SECRET_ACCESS_KEY\` | Your AWS secret access key |
| \`PULUMI_ACCESS_TOKEN\` | Your Pulumi access token ([get one here](https://app.pulumi.com/account/tokens)) |
`;

  const initInstructions =
    iacType === 'terraform'
      ? `
### Terraform State Backend

By default, Terraform stores state locally. For team collaboration, configure a remote backend:

\`\`\`hcl
# Add to main.tf
terraform {
  backend "s3" {
    bucket = "your-terraform-state-bucket"
    key    = "infrastructure/terraform.tfstate"
    region = "us-east-1"
  }
}
\`\`\`
`
      : `
### Pulumi State Backend

Create a new Pulumi stack:

\`\`\`bash
cd infrastructure
pulumi stack init dev
\`\`\`
`;

  return `# Infrastructure Deployment

This infrastructure was generated by [InfraCanvas](https://github.com/johnbekele/infracanvas).

## GitHub Actions Setup

### Required Secrets

Add these secrets to your repository (Settings > Secrets and variables > Actions):
${secrets}

${initInstructions}

## Manual Deployment

${
  iacType === 'terraform'
    ? `
\`\`\`bash
cd infrastructure
terraform init
terraform plan
terraform apply
\`\`\`
`
    : `
\`\`\`bash
cd infrastructure
${iacType === 'pulumi-ts' ? 'npm install' : 'pip install -r requirements.txt'}
pulumi up
\`\`\`
`
}

## Structure

\`\`\`
infrastructure/
${
  iacType === 'terraform'
    ? `├── main.tf          # Main configuration
├── variables.tf     # Input variables
├── outputs.tf       # Output values
├── providers.tf     # Provider configuration
└── modules/         # Reusable modules`
    : iacType === 'pulumi-ts'
      ? `├── index.ts         # Main Pulumi program
├── package.json     # Node.js dependencies
└── Pulumi.yaml      # Pulumi project config`
      : `├── __main__.py      # Main Pulumi program
├── requirements.txt # Python dependencies
└── Pulumi.yaml      # Pulumi project config`
}
\`\`\`
`;
}
