/**
 * What a dependency implies about the infrastructure a repository needs.
 *
 * A lookup table rather than a model. The mapping from `pg` to "this needs
 * Postgres" is a fact, not a judgement, and a table can be read, reviewed, and
 * corrected by anyone who disagrees with an entry. Where the mapping genuinely
 * is a judgement -- an ORM that supports several engines -- the entry records
 * the category and leaves the capability null rather than picking one.
 *
 * Coverage is the point. A dependency missing from this table is not a smaller
 * finding, it is silence: the component that declared it looks like it needs
 * nothing. That is why the AI and data sections are as detailed as the web
 * framework one, and why a package that only says "there is a model in here
 * somewhere" still earns an entry.
 */
import type { Capability, DependencyCategory, Ecosystem } from '@infracanvas/core';

export interface Signature {
  category: DependencyCategory;
  capability: Capability | null;
}

type SignatureTable = Record<string, Signature>;

const webFramework = (capability: Capability = 'http-server'): Signature => ({
  category: 'web-framework',
  capability,
});
const datastore = (capability: Capability): Signature => ({ category: 'datastore', capability });
const cache = (capability: Capability): Signature => ({ category: 'cache', capability });
const queue = (capability: Capability): Signature => ({ category: 'queue', capability });
const search = (capability: Capability): Signature => ({ category: 'search', capability });
const vector: Signature = { category: 'vector', capability: 'vector-search' };
const frontend: Signature = { category: 'frontend-framework', capability: 'frontend' };
/** Recognised, but the engine it talks to is a configuration choice, not a dependency. */
const ormOnly: Signature = { category: 'orm', capability: null };
const ml: Signature = { category: 'ml', capability: 'ml-inference' };
/** Needs an accelerator, which is a different instance family and a different bill. */
const gpu: Signature = { category: 'ml', capability: 'gpu-inference' };
const embeddings: Signature = { category: 'ml', capability: 'embeddings' };
/** Calls a hosted model, so it needs an endpoint and a key rather than a GPU. */
const llm: Signature = { category: 'llm', capability: 'llm-api' };
const agent: Signature = { category: 'agent', capability: 'llm-api' };
const document: Signature = { category: 'document', capability: 'document-processing' };
const workflow: Signature = { category: 'workflow', capability: 'workflow-orchestration' };
const jobs: Signature = { category: 'queue', capability: 'background-jobs' };
const scheduled: Signature = { category: 'queue', capability: 'scheduled-jobs' };
const observability: Signature = { category: 'observability', capability: 'observability' };
const identity: Signature = { category: 'auth', capability: 'identity' };
const email: Signature = { category: 'other', capability: 'email' };
const objectStorage = (category: DependencyCategory = 'cloud-sdk'): Signature => ({
  category,
  capability: 'object-storage',
});
const secrets: Signature = { category: 'cloud-sdk', capability: 'secrets' };
/** A cloud SDK broad enough that its presence implies no particular service. */
const cloudSdk: Signature = { category: 'cloud-sdk', capability: null };

const NPM: SignatureTable = {
  // Serving
  express: webFramework(),
  fastify: webFramework(),
  koa: webFramework(),
  '@hapi/hapi': webFramework(),
  '@nestjs/core': webFramework(),
  hono: webFramework(),
  restify: webFramework(),
  polka: webFramework(),
  elysia: webFramework(),
  h3: webFramework(),
  '@trpc/server': webFramework(),
  graphql: webFramework('graphql'),
  '@apollo/server': webFramework('graphql'),
  'apollo-server': webFramework('graphql'),
  'type-graphql': webFramework('graphql'),
  'graphql-yoga': webFramework('graphql'),
  mercurius: webFramework('graphql'),
  '@grpc/grpc-js': webFramework('grpc'),
  '@grpc/proto-loader': webFramework('grpc'),
  'nice-grpc': webFramework('grpc'),
  'socket.io': webFramework('websocket'),
  ws: webFramework('websocket'),
  '@fastify/websocket': webFramework('websocket'),
  '@modelcontextprotocol/sdk': webFramework('mcp-server'),
  // Front ends
  next: frontend,
  react: frontend,
  'react-dom': frontend,
  vue: frontend,
  nuxt: frontend,
  svelte: frontend,
  '@sveltejs/kit': frontend,
  '@angular/core': frontend,
  gatsby: frontend,
  remix: frontend,
  '@remix-run/react': frontend,
  astro: frontend,
  'solid-js': frontend,
  preact: frontend,
  '@builder.io/qwik': frontend,
  // Relational and document stores
  pg: datastore('postgres'),
  postgres: datastore('postgres'),
  'pg-promise': datastore('postgres'),
  'pg-pool': datastore('postgres'),
  '@neondatabase/serverless': datastore('postgres'),
  mysql: datastore('mysql'),
  mysql2: datastore('mysql'),
  '@planetscale/database': datastore('mysql'),
  mongodb: datastore('mongodb'),
  mongoose: datastore('mongodb'),
  '@aws-sdk/client-dynamodb': datastore('dynamodb'),
  dynamoose: datastore('dynamodb'),
  'cassandra-driver': datastore('cassandra'),
  '@clickhouse/client': datastore('clickhouse'),
  'neo4j-driver': datastore('graph-db'),
  gremlin: datastore('graph-db'),
  '@elastic/elasticsearch': search('elasticsearch'),
  '@opensearch-project/opensearch': search('elasticsearch'),
  // Caches
  redis: cache('redis'),
  ioredis: cache('redis'),
  '@upstash/redis': cache('redis'),
  memcached: cache('redis'),
  // Vector stores
  '@pinecone-database/pinecone': vector,
  '@qdrant/js-client-rest': vector,
  'weaviate-ts-client': vector,
  'weaviate-client': vector,
  chromadb: vector,
  '@lancedb/lancedb': vector,
  pgvector: vector,
  // Work
  kafkajs: queue('kafka'),
  '@confluentinc/kafka-javascript': queue('kafka'),
  amqplib: queue('rabbitmq'),
  'amqp-connection-manager': queue('rabbitmq'),
  bullmq: jobs,
  bull: jobs,
  agenda: jobs,
  'bee-queue': jobs,
  'pg-boss': jobs,
  'node-resque': jobs,
  '@aws-sdk/client-sqs': jobs,
  'node-cron': scheduled,
  cron: scheduled,
  'node-schedule': scheduled,
  croner: scheduled,
  '@temporalio/client': workflow,
  '@temporalio/worker': workflow,
  inngest: workflow,
  '@aws-sdk/client-sfn': workflow,
  // Models
  openai: llm,
  '@anthropic-ai/sdk': llm,
  '@google/generative-ai': llm,
  '@google/genai': llm,
  'cohere-ai': llm,
  '@mistralai/mistralai': llm,
  'groq-sdk': llm,
  '@aws-sdk/client-bedrock-runtime': llm,
  '@aws-sdk/client-bedrock-agent-runtime': llm,
  ollama: llm,
  replicate: llm,
  ai: agent,
  '@ai-sdk/openai': agent,
  '@ai-sdk/anthropic': agent,
  langchain: agent,
  '@langchain/core': agent,
  '@langchain/openai': agent,
  '@langchain/community': agent,
  '@langchain/langgraph': agent,
  llamaindex: agent,
  '@mastra/core': agent,
  '@xenova/transformers': embeddings,
  '@huggingface/inference': llm,
  '@tensorflow/tfjs-node': ml,
  'onnxruntime-node': ml,
  // Documents
  'pdf-parse': document,
  'pdfjs-dist': document,
  mammoth: document,
  'tesseract.js': document,
  exceljs: document,
  // Platform
  '@aws-sdk/client-s3': objectStorage(),
  '@google-cloud/storage': objectStorage(),
  minio: objectStorage('datastore'),
  '@aws-sdk/client-secrets-manager': secrets,
  '@aws-sdk/client-ssm': secrets,
  nodemailer: email,
  '@sendgrid/mail': email,
  resend: email,
  postmark: email,
  '@aws-sdk/client-ses': email,
  passport: identity,
  'next-auth': identity,
  '@auth/core': identity,
  '@clerk/clerk-sdk-node': identity,
  '@aws-sdk/client-cognito-identity-provider': identity,
  '@opentelemetry/api': observability,
  '@opentelemetry/sdk-node': observability,
  'prom-client': observability,
  '@sentry/node': observability,
  'dd-trace': observability,
  'aws-sdk': cloudSdk,
  '@aws-sdk/client-ec2': cloudSdk,
  // Support several engines, so the engine comes from their own configuration.
  prisma: ormOnly,
  '@prisma/client': ormOnly,
  typeorm: ormOnly,
  sequelize: ormOnly,
  knex: ormOnly,
  'drizzle-orm': ormOnly,
  '@mikro-orm/core': ormOnly,
  objection: ormOnly,
  kysely: ormOnly,
};

const PYPI: SignatureTable = {
  // Serving
  fastapi: webFramework(),
  flask: webFramework(),
  django: webFramework(),
  djangorestframework: webFramework(),
  starlette: webFramework(),
  tornado: webFramework(),
  bottle: webFramework(),
  sanic: webFramework(),
  falcon: webFramework(),
  litestar: webFramework(),
  quart: webFramework(),
  aiohttp: webFramework(),
  uvicorn: webFramework(),
  gunicorn: webFramework(),
  hypercorn: webFramework(),
  connexion: webFramework(),
  'strawberry-graphql': webFramework('graphql'),
  graphene: webFramework('graphql'),
  ariadne: webFramework('graphql'),
  grpcio: webFramework('grpc'),
  'grpcio-tools': webFramework('grpc'),
  websockets: webFramework('websocket'),
  channels: webFramework('websocket'),
  mcp: webFramework('mcp-server'),
  fastmcp: webFramework('mcp-server'),
  streamlit: frontend,
  gradio: frontend,
  dash: frontend,
  // Relational and document stores
  psycopg2: datastore('postgres'),
  'psycopg2-binary': datastore('postgres'),
  psycopg: datastore('postgres'),
  'psycopg-binary': datastore('postgres'),
  asyncpg: datastore('postgres'),
  pg8000: datastore('postgres'),
  pymysql: datastore('mysql'),
  mysqlclient: datastore('mysql'),
  aiomysql: datastore('mysql'),
  'mysql-connector-python': datastore('mysql'),
  pymongo: datastore('mongodb'),
  motor: datastore('mongodb'),
  beanie: datastore('mongodb'),
  mongoengine: datastore('mongodb'),
  'cassandra-driver': datastore('cassandra'),
  'clickhouse-connect': datastore('clickhouse'),
  'clickhouse-driver': datastore('clickhouse'),
  neo4j: datastore('graph-db'),
  py2neo: datastore('graph-db'),
  gremlinpython: datastore('graph-db'),
  elasticsearch: search('elasticsearch'),
  'elasticsearch-dsl': search('elasticsearch'),
  'opensearch-py': search('elasticsearch'),
  // Caches
  redis: cache('redis'),
  aioredis: cache('redis'),
  hiredis: cache('redis'),
  pymemcache: cache('redis'),
  // Vector stores
  pgvector: vector,
  'qdrant-client': vector,
  'pinecone-client': vector,
  pinecone: vector,
  'weaviate-client': vector,
  chromadb: vector,
  pymilvus: vector,
  lancedb: vector,
  'faiss-cpu': vector,
  'faiss-gpu': vector,
  usearch: vector,
  // Work
  celery: jobs,
  rq: jobs,
  dramatiq: jobs,
  huey: jobs,
  arq: jobs,
  taskiq: jobs,
  kombu: jobs,
  'kafka-python': queue('kafka'),
  aiokafka: queue('kafka'),
  'confluent-kafka': queue('kafka'),
  faust: queue('kafka'),
  pika: queue('rabbitmq'),
  'aio-pika': queue('rabbitmq'),
  apscheduler: scheduled,
  schedule: scheduled,
  temporalio: workflow,
  'apache-airflow': workflow,
  prefect: workflow,
  dagster: workflow,
  luigi: workflow,
  // Models: hosted APIs
  openai: llm,
  anthropic: llm,
  cohere: llm,
  mistralai: llm,
  'google-generativeai': llm,
  'google-genai': llm,
  litellm: llm,
  groq: llm,
  together: llm,
  replicate: llm,
  'huggingface-hub': llm,
  tiktoken: llm,
  // Models: agent frameworks
  langchain: agent,
  'langchain-core': agent,
  'langchain-community': agent,
  'langchain-openai': agent,
  langgraph: agent,
  'llama-index': agent,
  'llama-index-core': agent,
  'pydantic-ai': agent,
  crewai: agent,
  autogen: agent,
  pyautogen: agent,
  'semantic-kernel': agent,
  smolagents: agent,
  'dspy-ai': agent,
  dspy: agent,
  instructor: agent,
  guidance: agent,
  'haystack-ai': agent,
  // Models: local inference
  torch: ml,
  tensorflow: ml,
  transformers: ml,
  'scikit-learn': ml,
  onnxruntime: ml,
  'onnxruntime-gpu': gpu,
  jax: ml,
  flax: ml,
  keras: ml,
  xgboost: ml,
  lightgbm: ml,
  catboost: ml,
  spacy: ml,
  nltk: ml,
  vllm: gpu,
  accelerate: gpu,
  bitsandbytes: gpu,
  deepspeed: gpu,
  'flash-attn': gpu,
  xformers: gpu,
  tensorrt: gpu,
  peft: gpu,
  unsloth: gpu,
  'sentence-transformers': embeddings,
  fastembed: embeddings,
  // Documents
  pypdf: document,
  pypdf2: document,
  pdfplumber: document,
  pdf2image: document,
  pdfminer: document,
  'pdfminer.six': document,
  unstructured: document,
  'python-docx': document,
  'python-pptx': document,
  openpyxl: document,
  pytesseract: document,
  markitdown: document,
  docling: document,
  'camelot-py': document,
  layoutparser: document,
  // Platform
  boto3: cloudSdk,
  aioboto3: cloudSdk,
  botocore: cloudSdk,
  minio: objectStorage('datastore'),
  s3fs: objectStorage(),
  'aws-secretsmanager-caching': secrets,
  hvac: secrets,
  sendgrid: email,
  resend: email,
  aiosmtplib: email,
  authlib: identity,
  'python-keycloak': identity,
  msal: identity,
  'opentelemetry-api': observability,
  'opentelemetry-sdk': observability,
  'prometheus-client': observability,
  'sentry-sdk': observability,
  ddtrace: observability,
  feast: { category: 'ml', capability: 'feature-store' },
  mlflow: { category: 'ml', capability: 'feature-store' },
  // ORMs
  sqlalchemy: ormOnly,
  alembic: ormOnly,
  sqlmodel: ormOnly,
  'tortoise-orm': ormOnly,
  peewee: ormOnly,
};

const GO: SignatureTable = {
  'github.com/gin-gonic/gin': webFramework(),
  'github.com/labstack/echo': webFramework(),
  'github.com/gofiber/fiber': webFramework(),
  'github.com/gorilla/mux': webFramework(),
  'github.com/go-chi/chi': webFramework(),
  'github.com/beego/beego': webFramework(),
  'github.com/kataras/iris': webFramework(),
  'google.golang.org/grpc': webFramework('grpc'),
  'connectrpc.com/connect': webFramework('grpc'),
  'github.com/99designs/gqlgen': webFramework('graphql'),
  'github.com/gorilla/websocket': webFramework('websocket'),
  'github.com/lib/pq': datastore('postgres'),
  'github.com/jackc/pgx': datastore('postgres'),
  'github.com/go-sql-driver/mysql': datastore('mysql'),
  'go.mongodb.org/mongo-driver': datastore('mongodb'),
  'github.com/gocql/gocql': datastore('cassandra'),
  'github.com/clickhouse/clickhouse-go': datastore('clickhouse'),
  'github.com/neo4j/neo4j-go-driver': datastore('graph-db'),
  'github.com/aws/aws-sdk-go-v2/service/dynamodb': datastore('dynamodb'),
  'github.com/redis/go-redis': cache('redis'),
  'github.com/go-redis/redis': cache('redis'),
  'github.com/bradfitz/gomemcache': cache('redis'),
  'github.com/qdrant/go-client': vector,
  'github.com/segmentio/kafka-go': queue('kafka'),
  'github.com/confluentinc/confluent-kafka-go': queue('kafka'),
  'github.com/ibm/sarama': queue('kafka'),
  'github.com/shopify/sarama': queue('kafka'),
  'github.com/rabbitmq/amqp091-go': queue('rabbitmq'),
  'github.com/hibiken/asynq': jobs,
  'github.com/riverqueue/river': jobs,
  'github.com/aws/aws-sdk-go-v2/service/sqs': jobs,
  'github.com/robfig/cron': scheduled,
  'go.temporal.io/sdk': workflow,
  'github.com/sashabaranov/go-openai': llm,
  'github.com/tmc/langchaingo': agent,
  'github.com/elastic/go-elasticsearch': search('elasticsearch'),
  'github.com/opensearch-project/opensearch-go': search('elasticsearch'),
  'github.com/aws/aws-sdk-go-v2/service/s3': objectStorage(),
  'github.com/minio/minio-go': objectStorage('datastore'),
  'github.com/aws/aws-sdk-go-v2/service/secretsmanager': secrets,
  'go.opentelemetry.io/otel': observability,
  'github.com/prometheus/client_golang': observability,
  'github.com/getsentry/sentry-go': observability,
  'github.com/aws/aws-sdk-go-v2': cloudSdk,
  'github.com/aws/aws-sdk-go': cloudSdk,
  'gorm.io/gorm': ormOnly,
  'entgo.io/ent': ormOnly,
  'github.com/jmoiron/sqlx': ormOnly,
  'github.com/uptrace/bun': ormOnly,
};

const CARGO: SignatureTable = {
  axum: webFramework(),
  'actix-web': webFramework(),
  rocket: webFramework(),
  warp: webFramework(),
  poem: webFramework(),
  salvo: webFramework(),
  tide: webFramework(),
  tonic: webFramework('grpc'),
  'async-graphql': webFramework('graphql'),
  'tokio-tungstenite': webFramework('websocket'),
  'tokio-postgres': datastore('postgres'),
  postgres: datastore('postgres'),
  'deadpool-postgres': datastore('postgres'),
  mysql: datastore('mysql'),
  mysql_async: datastore('mysql'),
  mongodb: datastore('mongodb'),
  scylla: datastore('cassandra'),
  clickhouse: datastore('clickhouse'),
  neo4rs: datastore('graph-db'),
  'aws-sdk-dynamodb': datastore('dynamodb'),
  redis: cache('redis'),
  fred: cache('redis'),
  'qdrant-client': vector,
  lancedb: vector,
  rdkafka: queue('kafka'),
  lapin: queue('rabbitmq'),
  apalis: jobs,
  celery: jobs,
  elasticsearch: search('elasticsearch'),
  'async-openai': llm,
  'ollama-rs': llm,
  'candle-core': ml,
  'tract-onnx': ml,
  ort: ml,
  tch: ml,
  fastembed: embeddings,
  'aws-sdk-s3': objectStorage(),
  object_store: objectStorage(),
  'aws-sdk-secretsmanager': secrets,
  opentelemetry: observability,
  prometheus: observability,
  sentry: observability,
  sqlx: ormOnly,
  diesel: ormOnly,
  'sea-orm': ormOnly,
};

const MAVEN: SignatureTable = {
  'spring-boot-starter-web': webFramework(),
  'spring-boot-starter-webflux': webFramework(),
  'quarkus-resteasy': webFramework(),
  'micronaut-http-server-netty': webFramework(),
  'vertx-web': webFramework(),
  javalin: webFramework(),
  'dropwizard-core': webFramework(),
  'grpc-netty': webFramework('grpc'),
  'graphql-java': webFramework('graphql'),
  postgresql: datastore('postgres'),
  'mysql-connector-java': datastore('mysql'),
  'mysql-connector-j': datastore('mysql'),
  'mariadb-java-client': datastore('mysql'),
  'mongodb-driver-sync': datastore('mongodb'),
  'mongodb-driver-reactivestreams': datastore('mongodb'),
  'java-driver-core': datastore('cassandra'),
  'clickhouse-jdbc': datastore('clickhouse'),
  'neo4j-java-driver': datastore('graph-db'),
  jedis: cache('redis'),
  'lettuce-core': cache('redis'),
  'spring-boot-starter-data-redis': cache('redis'),
  'kafka-clients': queue('kafka'),
  'spring-kafka': queue('kafka'),
  'amqp-client': queue('rabbitmq'),
  'spring-boot-starter-amqp': queue('rabbitmq'),
  'activemq-client': queue('rabbitmq'),
  'spring-boot-starter-quartz': scheduled,
  'elasticsearch-rest-high-level-client': search('elasticsearch'),
  'opensearch-rest-client': search('elasticsearch'),
  langchain4j: agent,
  'openai-java': llm,
  'aws-java-sdk-s3': objectStorage(),
  s3: objectStorage(),
  'opentelemetry-api': observability,
  'micrometer-core': observability,
  'sentry-spring-boot-starter': observability,
  'spring-boot-starter-security': identity,
  'spring-boot-starter-mail': email,
  'spring-boot-starter-data-jpa': ormOnly,
  'hibernate-core': ormOnly,
  mybatis: ormOnly,
};

const RUBYGEMS: SignatureTable = {
  rails: webFramework(),
  sinatra: webFramework(),
  puma: webFramework(),
  unicorn: webFramework(),
  rack: webFramework(),
  grape: webFramework(),
  roda: webFramework(),
  hanami: webFramework(),
  graphql: webFramework('graphql'),
  pg: datastore('postgres'),
  mysql2: datastore('mysql'),
  mongoid: datastore('mongodb'),
  'cassandra-driver': datastore('cassandra'),
  redis: cache('redis'),
  'redis-rb': cache('redis'),
  dalli: cache('redis'),
  sidekiq: jobs,
  resque: jobs,
  delayed_job: jobs,
  sucker_punch: jobs,
  good_job: jobs,
  shoryuken: jobs,
  karafka: queue('kafka'),
  bunny: queue('rabbitmq'),
  whenever: scheduled,
  'rufus-scheduler': scheduled,
  clockwork: scheduled,
  elasticsearch: search('elasticsearch'),
  searchkick: search('elasticsearch'),
  'opensearch-ruby': search('elasticsearch'),
  'ruby-openai': llm,
  anthropic: llm,
  'aws-sdk-s3': objectStorage(),
  'fog-aws': objectStorage(),
  'aws-sdk-secretsmanager': secrets,
  'sentry-ruby': observability,
  'opentelemetry-sdk': observability,
  'prometheus-client': observability,
  devise: identity,
  mail: email,
  activerecord: ormOnly,
  sequel: ormOnly,
};

const COMPOSER: SignatureTable = {
  'laravel/framework': webFramework(),
  'symfony/framework-bundle': webFramework(),
  'slim/slim': webFramework(),
  'cakephp/cakephp': webFramework(),
  'yiisoft/yii2': webFramework(),
  'laminas/laminas-mvc': webFramework(),
  'webonyx/graphql-php': webFramework('graphql'),
  'mongodb/mongodb': datastore('mongodb'),
  'predis/predis': cache('redis'),
  'elasticsearch/elasticsearch': search('elasticsearch'),
  'opensearch-project/opensearch-php': search('elasticsearch'),
  'php-amqplib/php-amqplib': queue('rabbitmq'),
  'enqueue/enqueue': jobs,
  'symfony/messenger': jobs,
  'openai-php/client': llm,
  'aws/aws-sdk-php': cloudSdk,
  'league/flysystem-aws-s3-v3': objectStorage(),
  'sentry/sentry': observability,
  'symfony/mailer': email,
  'swiftmailer/swiftmailer': email,
  'doctrine/orm': ormOnly,
  'illuminate/database': ormOnly,
};

const TABLES: Record<Ecosystem, SignatureTable> = {
  npm: NPM,
  pypi: PYPI,
  go: GO,
  cargo: CARGO,
  maven: MAVEN,
  rubygems: RUBYGEMS,
  composer: COMPOSER,
};

/**
 * Look up a dependency, returning null when it is not one this table knows.
 *
 * Go module paths are matched by prefix because they carry a major version
 * suffix (`/v5`) and often a submodule path, neither of which changes what the
 * dependency implies. Python names are normalised because the ecosystem treats
 * `-`, `_` and `.` as equivalent, so `llama_index` and `llama-index` are one
 * package. Everything else is matched exactly and case-insensitively.
 */
export function lookupSignature(ecosystem: Ecosystem, name: string): Signature | null {
  const table = TABLES[ecosystem];
  const normalised = name.toLowerCase();

  const exact = table[normalised];
  if (exact) return exact;

  if (ecosystem === 'pypi') {
    const canonical = normalised.replace(/[_.]/g, '-');
    const byCanonical = table[canonical];
    if (byCanonical) return byCanonical;
  }

  if (ecosystem === 'go') {
    // Longest first, so `.../aws-sdk-go-v2/service/s3` is not claimed by the
    // generic `.../aws-sdk-go-v2` entry sitting above it.
    const prefixes = Object.keys(table).sort((a, b) => b.length - a.length);
    for (const prefix of prefixes) {
      if (normalised === prefix || normalised.startsWith(`${prefix}/`)) return table[prefix];
    }
  }

  return null;
}
